  volatile char *dirf = (char*)0x30;//DDRF – Port F Data Direction Register
  volatile char *dirk = (char*)0x107;//DDRK – Port K Data Direction Register
  volatile char *dira = (char*)0x21;//DDRA – Port F Data Direction Register
  volatile char *dirc = (char*)0x27;//DDRC – Port K Data Direction Register
  volatile char *outf = (char*)0x31;//PORTF – Port F Data Register
  volatile char *outk = (char*)0x108;//PORTK – Port F Data Register
  volatile char *outa = (char*)0x22;//PORTA – Port F Data Register
  volatile char *outc = (char*)0x28;//PORTC – Port F Data Register
  volatile char *ink = (char*)0x106;// PINK – Port K Input Pins Address